import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '@/app/globals.css';
import TopBar from '@/components/TopBar';
import { Locale } from '@/dictionaries';

const nunitoSans = localFont({ src: '../../public/fonts/NunitoSans.ttf', weight: '400' });

export const metadata: Metadata = {
  title: 'CLEAR',
  description: 'Generated by create next app',
};

const RootLayout = async ({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ lang: Locale }>;
}) => {
  const { lang } = await params;

  return (
    <html lang={lang}>
      <body className={`${nunitoSans.className} flex flex-col antialiased`}>
        <TopBar lang={lang} />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
